### ISSUE TITLE
[hamburger menu] refactor connect another device to use FxA-client component

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services-bug-mirror#180]
This is non-blocking, but a nice-to-fix.

The Connect another device functionality on the Firefox about:preferences#sync page should be updated to use the fxa-client.

Acceptance Criteria:
- TBD

---
🐞 Issue is synchronized with Bugzilla [Bug 1633478](https://bugzilla.mozilla.org/show_bug.cgi?id=1633478)

**Comment by jdragojevic** [comment]
dup
