### ISSUE TITLE
[accounts toolbar menu] refactor Send Tab to use FxA-client component

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services-bug-mirror#181]
The Send tab functionality on the Firefox account toolbar menu should be updated to use the fxa-client.

The scope of this bug is limited to initiating a Send tab from the accounts toolbar menu, but does not include the push notifications to destination devices.

Acceptance criteria:
- List of available devices is correctly displayed when opening the Send tab to Device sub-menu item
- Tab is successfully delivered to a single, multiple or all devices
- Logs indicated that we're using the new fxa-client

---
🐞 Issue is synchronized with Bugzilla [Bug 1633480](https://bugzilla.mozilla.org/show_bug.cgi?id=1633480)

**Comment by jdragojevic** [comment]
dup
