### ISSUE TITLE
Refactor the "pre-account" telemetry ping into the "Account Ecosystem" ping

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services-bug-mirror#223]
Bug 1529232 landed a "pre-account ecosystem ping" as a first step towards more general ecosystem telemetry infrastructure. However, the design of the system changed since that ping was landed, and it was eventually preffed off in Bug 1613692. The code is still in the tree though:

  * https://searchfox.org/mozilla-central/rev/a4d62e09a4c46aef918667fa759bf9ae898dc258/toolkit/components/telemetry/pings/EcosystemTelemetry.jsm

From a bit of poking around, I think we can refactor this ping to be the general "Account Ecosystem ping" without doing *too* much surgery, and that's likely to be easier than trying to make a new ping from scratch.

As background, the major changes to ecosystem telemetry since this ping landed are:

* The previous design separated data into a "pre-account" ping sent by all clients, and a "post-account" ping sent only by signed-in clients. The current design has only a single "account ecosystem" ping sent by all clients.
* The previous design included a `uid` field that was a HMAC of the user's FxA account uid. The current design uses an identifier that's harder to link back to a specific account, called `ecosystemAnonId`.

Items to tackle as part of this refactor:

* We need to agree on the final schema for this ping and update the in-tree docs to match; see discussion in https://github.com/mozilla/gcp-ingestion/pull/1264
* The ping needs to be submitted to a special endpoint for routing purposes; again, ref https://github.com/mozilla/gcp-ingestion/pull/1264
* The ping should only be sent for signed-in users, and should obtain the `ecosystemAnonId` value using the facilities provided by Bug 1635656.
* IIUC the sending of this ping is currently preffed off by default, and we should keep it that way to start.
* IIUC the ping currently includes just two metrics (`total_uri_count` and `active_ticks`) and we should keep them in the ping, but re-name the store in [Scalars.yaml](https://searchfox.org/mozilla-central/rev/a4d62e09a4c46aef918667fa759bf9ae898dc258/toolkit/components/telemetry/Scalars.yaml#243)
* A new round of data-review.

:janerik, you did the work on the `pre-account` ping, does this seem like a reasonable plan to you?

---
🐞 Issue is synchronized with Bugzilla [Bug 1635659](https://bugzilla.mozilla.org/show_bug.cgi?id=1635659)

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
