### ISSUE TITLE
Use reliable scheduling mechanism for ecosystem ping

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services-bug-mirror#224]
(I straight-up stole this from Bug 1535336, to include it in the new ecosystem telemetry metabug)

The current ecosystem elemetry ping implements scheduling by listening to `idle-daily` events.

This is not reliable, it is not guaranteed to be called and the schedule is unclear.
If we want a reliable 24h schedule we need a different mechanism.

---
🐞 Issue is synchronized with Bugzilla [Bug 1635660](https://bugzilla.mozilla.org/show_bug.cgi?id=1635660)

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: WORKSFORME.
