### ISSUE TITLE
Add ecosystemClientId to the Accounts Ecosystem Telemetry ping

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services-bug-mirror#225]
As described in [Account Ecosysten Telemetry Identifiers](https://docs.google.com/document/d/1rR3uJG8sVtow4plYu6M5Jp5e5zOSrLzdkUx8BdO8kOM/), the AET ping needs to include an `ecosystemClientId` field that is very similar to, but not linked to, the main-ping `clientId`.  This is a randomly-generated identifier that is unique to a particular Firefox profile.

We will need to:

* Manage persistence of such an identifier, creating a new random one if it doesn't already exist
* Arrange for it to be included in the ecosystem telemetry ping that results from Bug 1635659.
* Arrange for it to be included in the `deletion-request` ping for users who opt out of telemetry.

I haven't looked into the details of doing this at all, but I'm kind of hopeful that we can wholesale copy how the main telemetry `clientId` is managed...

---
🐞 Issue is synchronized with Bugzilla [Bug 1635662](https://bugzilla.mozilla.org/show_bug.cgi?id=1635662)

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
