### ISSUE TITLE
Lockwise merges different user's credentials

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services-bug-mirror#347]
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

Steps to reproduce:

I had an account in Firefox in my pc. 
This account had my login credentials in Lockwise.
I logged off from this account, created a new one with a different email and logged in from it at the same pc.

Actual results:

While logged in with different account the credentials from my account were visible in Lockwise.
Lockwise merged the credentials of the two accounts.
Furthermore, after sync they were also available from other computers.

Expected results:

Each account should have only it's own user credentials. No merging of credentials should be done.

---
🐞 Issue is synchronized with Bugzilla [Bug 1650544](https://bugzilla.mozilla.org/show_bug.cgi?id=1650544)

**Comment by rfk** [comment]
Accidental dupe, closing
