### ISSUE TITLE
Allow OAuth access to the "devices" API

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services-bug-mirror#6]
Mirror of https://github.com/mozilla/fxa-auth-server/issues/2547

----

There's lots of discussion in the linked bug that I won't duplicate here, but the premise is to update the FxA "devices" API so that it can be used by clients holding a refreshToken with "oldsync" scope.

**Comment by jdragojevic** [comment]
This is done.

@rfk can you open permission on this repo please so tickets can be updated via waffle.

**Comment by rfk** [comment]
> @rfk can you open permission on this repo please so tickets can be updated via waffle.

👍 . The "application-services" team has access, but you're not in it - I think we were originally wondering whether you needed to be in it as a security-boundary-minimisation exercise, but from this it seems like you should be. I've invited you.
