### ISSUE TITLE
Decide whether a separate "bug mirror" repo is a useful concept

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services-bug-mirror#8]
After discussion with @vladikoff and taking a leaf from [fxa-bugzilla-mirror](https://github.com/mozilla/fxa-bugzilla-mirror), I've created an experimental [application-services-bug-mirror](https://github.com/mozilla/application-services-bug-mirror/) repo into which we can mirror issues from other sources that need to feed in to our planning work.

Right now I've just mirrored a couple of issues by hand to try it out.

If we feel like this is useful, we could invest in some automation to periodically copy issues from e.g. fxa, a-c and other github boards, or even from bugzilla.

Alternately, we might find that having them in a separate repo is a bit janky/weird and just move the issues and any automation over to the main a-s repo.

Alternately, we could decide it's just not particularly useful and abandon the experiment altogether.

Let me know what you think!

**Comment by vladikoff** [comment]
* we can create issues on the main repo
* we need to decide where do we go from waffle

**Comment by rfk** [comment]
Seeing as waffle has gone away, I'm going to retire this repo and migrate its remaining one issue over to the main application-services repo.
